# Generated by Django 4.0.4 on 2022-05-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('subtitle', models.CharField(max_length=200, unique=True)),
                ('content', models.TextField()),
                ('image', models.ImageField(default='blogs/default_blog_image.jpg', upload_to='blogs/%Y/%m/%d')),
                ('date', models.DateTimeField(auto_now=True)),
                ('avaiable', models.BooleanField(default=True)),
            ],
        ),
    ]
