# Generated by Django 4.0.4 on 2022-05-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='media/default_blog_image.jpg', upload_to='blogs/%Y/%m/%d/'),
        ),
    ]
