# Generated by Django 4.0.4 on 2022-05-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0004_alter_trainer_description_alter_trainer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='description',
            field=models.TextField(max_length=70),
        ),
    ]
