# Generated by Django 4.0.4 on 2022-05-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0005_alter_trainer_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainer',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='trainer',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
